In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import neighbors,datasets,preprocessing
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,BernoulliNB
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
iris =datasets.load_iris()
X,y=iris.data[:,:],iris.target
print(y)
p=iris.target_names
print(p)
X_train,X_test,y_train,y_test=train_test_split(X,y,stratify=y,random_state=0,train_size=0.3)
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
scores=[]
classifier=GaussianNB()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
scores.append(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(scores)
scores1=[]
classifier1=GaussianNB()
classifier1.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
scores1.append(accuracy_score(y_test,y_pred))
cm1=confusion_matrix(y_test,y_pred)
print(cm1)
print(scores1)
print("Classification Report")
print(classification_report(y_test,y_pred))


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']
[[35  0  0]
 [ 0 31  4]
 [ 0  2 33]]
[0.9428571428571428]
[[35  0  0]
 [ 0 31  4]
 [ 0  2 33]]
[0.9428571428571428]
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       0.94      0.89      0.91        35
           2       0.89      0.94      0.92        35

    accuracy                           0.94       105
   macro avg       0.94      0.94      0.94       105
weighted avg       0.94      0.94      0.94       105

